/* Easy Nivesh shared app */
const $= (s,el=document)=>el.querySelector(s);
const $$=(s,el=document)=>[...el.querySelectorAll(s)];
const inr=n=>{if(n==null||n===""||Number.isNaN(+n))return"—";return"₹"+Math.round(+n).toLocaleString("en-IN")};
const esc=s=>{const a=String.fromCharCode(38);return String(s??"").replace(/&/g,a+"amp;").replace(/</g,a+"lt;").replace(/>/g,a+"gt;").replace(/"/g,a+"quot;").replace(/'/g,a+"#39;")};
const DAY=864e5;
const T=(()=>{const d=new Date();d.setHours(0,0,0,0);return d.getTime()})();
const fd=d=>{if(d==null||d==="")return"—";const x=d instanceof Date?d:new Date(d);if(Number.isNaN(+x))return String(d);return x.toLocaleDateString("en-IN",{day:"numeric",month:"short"})};
const NAV=[{href:"index.html",label:"Home",page:"home"},{href:"new-to-finance.html",label:"Start here",page:"start",cta:true},{href:"ipo.html",label:"IPOs",page:"ipo"},{href:"gold-etf.html",label:"Gold & ETF",page:"gold"},{href:"mutual-funds.html",label:"Mutual Funds",page:"mf"},{href:"equity.html",label:"Equity",page:"eq"}];
function closeNav(){document.body.classList.remove("nav-open");const btn=$("#navToggle");if(btn){btn.setAttribute("aria-expanded","false");btn.setAttribute("aria-label","Open menu")}}
function openNav(){document.body.classList.add("nav-open");const btn=$("#navToggle");if(btn){btn.setAttribute("aria-expanded","true");btn.setAttribute("aria-label","Close menu")}}
function toggleNav(){if(document.body.classList.contains("nav-open"))closeNav();else openNav()}
function layout(){const page=document.body.dataset.page||"";const hdr=$("#hdr");if(hdr){hdr.innerHTML=`<header class="hdr"><div class="hdr-in"><a class="logo" href="index.html" aria-label="Easy Nivesh home"><img src="assets/logo.svg?v=19" width="36" height="36" alt="Easy Nivesh" class="logo-img" id="brandLogo" style="object-fit:contain;background:transparent;display:block"><span class="logo-txt">Easy <span>Nivesh</span></span></a><button type="button" class="nav-toggle" id="navToggle" aria-label="Open menu" aria-expanded="false" aria-controls="primaryNav"><svg class="ico-open" width="22" height="22" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg><svg class="ico-close" width="22" height="22" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 6l12 12M18 6L6 18" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg></button></div></header><nav class="nav" id="primaryNav" aria-label="Primary">${NAV.map(n=>`<a href="${n.href}" class="${n.cta?"start":""}" ${n.page===page?'aria-current="page"':""}>${n.label}</a>`).join("")}</nav>`}const img=hdr&&hdr.querySelector(".logo-img");if(img){img.style.display="block";img.onerror=function(){this.onerror=null;if(window.PV_LOGO)this.src=window.PV_LOGO;else this.src="assets/logo.svg?v=19"};(function(){var s=document.createElement("script");s.src="assets/logo-data.js?v=19";s.onload=function(){if(window.PV_LOGO&&img)img.src=window.PV_LOGO};document.head.appendChild(s)})()}const toggle=$("#navToggle");if(toggle)toggle.addEventListener("click",toggleNav);const backdrop=$(".nav-backdrop")||document.createElement("div");if(!backdrop.classList.contains("nav-backdrop")){backdrop.className="nav-backdrop";document.body.appendChild(backdrop)}backdrop.addEventListener("click",closeNav);$$("#primaryNav a").forEach(function(a){a.addEventListener("click",closeNav)});if(document.title&&document.title.indexOf("Portfolio View India")>=0){document.title=document.title.split("Portfolio View India").join("Easy Nivesh")}fillMarketRibbon()}
function fillMarketRibbon(){let host=$(".mkt-ribbon");if(!host){host=document.createElement("div");host.className="mkt-ribbon";host.setAttribute("aria-label","Market snapshot");const hdr=$("#hdr");if(hdr&&hdr.parentNode)hdr.parentNode.insertBefore(host,hdr.nextSibling);else document.body.insertBefore(host,document.body.firstChild)}const items=[{t:"NIFTY 50",v:"—",href:"equity.html"},{t:"BANK NIFTY",v:"—",href:"equity.html"},{t:"IPO",v:"Check live",href:"ipo.html"},{t:"GOLD 24K",v:"—",href:"gold-etf.html"},{t:"Easy Nivesh",v:"Free guide to investing in India",href:"new-to-finance.html"}];const row=items.map(i=>`<a class="mkt-item" href="${i.href}"><span>${esc(i.t)}</span><b>${esc(i.v)}</b></a>`).join("");host.innerHTML=`<div class="mkt-track">${row}${row}</div>`;getGold().then(G=>{try{const c=G.j.cities&&G.j.cities[0];if(c){host.querySelectorAll(".mkt-item").forEach(el=>{if(el.textContent.indexOf("GOLD")>=0){const b=el.querySelector("b");if(b)b.textContent=inr(c.k24*10)+" /10g"}})}}catch(e){}}).catch(()=>{});getIpo().then(I=>{try{const list=(I.j&&(I.j.open||I.j.ipos||I.j.items))||[];const arr=Array.isArray(list)?list:[];const top=arr[0];if(top){const name=top.company||top.name||"IPO";const gmp=top.gmp!=null?top.gmp:top.GMP;host.querySelectorAll(".mkt-item").forEach(el=>{if(el.getAttribute("href")==="ipo.html"&&el.textContent.indexOf("IPO")>=0){const b=el.querySelector("b");if(b)b.textContent=name+(gmp!=null?" · GMP "+gmp:"")}})}}catch(e){}}).catch(()=>{})}
async function getJSON(file,demo){try{const r=await fetch("data/"+file+"?t="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error("missing");const j=await r.json();return{live:true,j,file,source:j.source||"data",source_url:j.source_url||"#",updated:j.updated_at||j.updated}}catch(e){return{live:false,j:demo,file,source:"demo",source_url:"#"}}}
const DEMO_GOLD={cities:[{city:"Mumbai",k24:7250,k22:6650},{city:"Delhi",k24:7240,k22:6640}],updated_at:null};
const DEMO_IPO={open:[],upcoming:[],updated_at:null};
function getGold(){return getJSON("gold.json",DEMO_GOLD)}
function getIpo(){return getJSON("ipo.json",DEMO_IPO)}
function getIPO(){return getIpo()}
function fmtIST(updated){if(!updated)return"—";const t=Date.parse(updated);if(Number.isNaN(t))return String(updated);return new Date(t).toLocaleString("en-IN",{timeZone:"Asia/Kolkata",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit",hour12:false})+" IST"}
function statusBar(el,result,retryFn){if(!el)return;const live=result&&result.live;const updated=result&&(result.updated||(result.j&&result.j.updated_at));const src=(result&&result.source)||"—";const srcUrl=(result&&result.source_url)||"#";let ageH=0;if(updated){const t=Date.parse(updated);if(!Number.isNaN(t))ageH=(Date.now()-t)/36e5}const stale=live&&ageH>36;let html="";if(!live){el.className="status warn";html=`◐ Demo data shown. Add data/${result.file||"…"} from the update script to go live.`}else if(stale){el.className="status warn";html=`⚠ Data may be out of date · Updated ${fmtIST(updated)} · Source: <a href="${esc(srcUrl)}" target="_blank" rel="noopener">${esc(src)} ↗</a>`}else{el.className="status";html=`● Live · Updated ${fmtIST(updated)} · Source: <a href="${esc(srcUrl)}" target="_blank" rel="noopener">${esc(src)} ↗</a>`}el.innerHTML=html}
function segs(container,cb){if(!container)return;container.addEventListener("click",e=>{const b=e.target.closest("button");if(!b||!container.contains(b))return;$$("button",container).forEach(x=>x.classList.remove("on"));b.classList.add("on");cb(b.dataset.v)})}
const AGES=[["20–24",75,15,10],["25–29",70,20,10],["30–39",60,30,10],["40–49",50,40,15],["50+",35,50,15]];
const MIXC=["var(--c2)","var(--blue)","var(--c4)"];
const MIXN=["Equity","Debt","Gold"];
function mixFor(ageIndex,riskShift){const row=AGES[ageIndex]||AGES[1];let eq=Math.max(10,Math.min(90,row[1]+(+riskShift||0)));const gold=row[3];return[eq,100-eq-gold,gold]}
function drawMix(donutEl,legendEl,values){if(!donutEl)return;const[e,d,g]=values;donutEl.style.background=`conic-gradient(${MIXC[0]} 0% ${e}%, ${MIXC[1]} ${e}% ${e+d}%, ${MIXC[2]} ${e+d}% 100%)`;if(legendEl){legendEl.innerHTML=MIXN.map((n,i)=>`<div class="row"><span><span class="dot" style="background:${MIXC[i]}"></span>${n}</span><b class="num">${values[i]}%</b></div>`).join("")}}
document.addEventListener("DOMContentLoaded",layout);
